# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='password',
        ),
    ]
