# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='lname',
        ),
    ]
