# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 22:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('logins', django.db.models.manager.Manager()),
            ],
        ),
    ]
