# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20190221_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bday',
        ),
    ]
