// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using secrets.Models;

namespace secrets.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190321190557_FirstMigrate")]
    partial class FirstMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("secrets.Models.Like", b =>
                {
                    b.Property<int>("likeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("secretId");

                    b.Property<int>("userId");

                    b.HasKey("likeId");

                    b.HasIndex("secretId");

                    b.HasIndex("userId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("secrets.Models.Secret", b =>
                {
                    b.Property<int>("secretId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("content")
                        .IsRequired();

                    b.Property<DateTime>("created_at");

                    b.Property<int?>("creatorUserId");

                    b.HasKey("secretId");

                    b.HasIndex("creatorUserId");

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("secrets.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("fName")
                        .IsRequired();

                    b.Property<string>("lName")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("secrets.Models.Like", b =>
                {
                    b.HasOne("secrets.Models.Secret", "secret")
                        .WithMany("likes")
                        .HasForeignKey("secretId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("secrets.Models.User", "user")
                        .WithMany("likes")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("secrets.Models.Secret", b =>
                {
                    b.HasOne("secrets.Models.User", "creator")
                        .WithMany("created")
                        .HasForeignKey("creatorUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
