# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-01 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge3', '0003_auto_20190117_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash_email',
            field=models.BinaryField(default='death', max_length=255),
        ),
    ]
