# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge3', '0005_auto_20190301_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash_email',
            field=models.CharField(default='$2b$12$CNGgp0CgCijJ4gjVjVn8RO6DqaM6b11GcesJMCewrFaNS./ZJrCLC', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
