// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using activityPlanner.Models;

namespace activityPlanner.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190326195142_onMigrate")]
    partial class onMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("activityPlanner.Models.Event", b =>
                {
                    b.Property<int>("eventId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<int?>("creatorUserId");

                    b.Property<DateTime>("date");

                    b.Property<string>("desc")
                        .IsRequired();

                    b.Property<int>("durInt");

                    b.Property<string>("durVal")
                        .IsRequired();

                    b.Property<DateTime>("time");

                    b.Property<string>("title")
                        .IsRequired();

                    b.HasKey("eventId");

                    b.HasIndex("creatorUserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("activityPlanner.Models.Participant", b =>
                {
                    b.Property<int>("participantId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("eventId");

                    b.Property<int>("userId");

                    b.HasKey("participantId");

                    b.HasIndex("eventId");

                    b.HasIndex("userId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("activityPlanner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("fName")
                        .IsRequired();

                    b.Property<string>("lName")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("activityPlanner.Models.Event", b =>
                {
                    b.HasOne("activityPlanner.Models.User", "creator")
                        .WithMany("createdEvents")
                        .HasForeignKey("creatorUserId");
                });

            modelBuilder.Entity("activityPlanner.Models.Participant", b =>
                {
                    b.HasOne("activityPlanner.Models.Event", "theEvent")
                        .WithMany("participants")
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("activityPlanner.Models.User", "theUser")
                        .WithMany("participations")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
