# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
